# ... Deployment YAML definition
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-k8s-configuration
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-k8s-configuration
  template:
    metadata:
      labels:
        app: spring-k8s-configuration
    spec:
      containers:
        - name: spring-k8s-configuration
          image: aqua-len/spring-k8s-configuration
          ports:
            - containerPort: 8080
          imagePullPolicy: Never
          env:
            - name: OBJECT_NAME
              valueFrom:
                secretKeyRef:
                  name: objects-config
                  key: object.name
            - name: COLORS
              valueFrom:
                secretKeyRef:
                  name: objects-config
                  key: colors
          volumeMounts:
            - name: colors-data
              mountPath: "/deployments/colors-data"
              readOnly: true
      volumes:
        - name: colors-data
          secret:
            secretName: objects-config
            items:
              - key: colors
                path: colors