# ... Deployment YAML definition
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-k8s-configuration
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-k8s-configuration
  template:
    metadata:
      labels:
        app: spring-k8s-configuration
    spec:
      containers:
        - name: spring-k8s-configuration
          image: aqua-len/spring-k8s-configuration
          ports:
            - containerPort: 8080
          env:
            - name: OBJECT_NAME
              value: snow board
            - name: COLORS
              value: red,blue,green
          imagePullPolicy: Never
---
# ... Service YAML definition
apiVersion: v1
kind: Service
metadata:
  name: spring-k8s-configuration
spec:
  type: NodePort
  selector:
    app: spring-k8s-configuration
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
---
# ... Ingress YAML definition
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spring-k8s-configuration
  annotations:
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - host: spring-k8s-configuration.info
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: spring-k8s-configuration
                port:
                  number: 8080